on:
  workflow_dispatch:

name: Check Venue Statuses

jobs:
  check_cineworld:
    name: Check Cineworld
    runs-on: self-hosted
    env:
      TZ: Europe/London
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - run: npm install
      - run: node node_modules/scripts/analysis/check-cineworld-ids.js

  check_curzon:
    name: Check Curzon
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - run: npm install
      - run: npx playwright install --with-deps
      - run: node node_modules/scripts/analysis/check-curzon-ids.js

  check_everyman:
    name: Check Everyman
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - run: npm install
      - run: node node_modules/scripts/analysis/check-everyman-ids.js

  check_myvue:
    name: Check Vue
    runs-on: self-hosted
    env:
      TZ: Europe/London
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - run: npm install
      - run: node node_modules/scripts/analysis/check-myvue-ids.js

  check_odeon:
    name: Check Odeon
    runs-on: self-hosted
    env:
      TZ: Europe/London
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - run: npm install
      - run: npx playwright install --with-deps
      - run: node node_modules/scripts/analysis/check-odeon-ids.js

  check_omniplex:
    name: Check Omniplex
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - run: npm install
      - run: node node_modules/scripts/analysis/check-omniplex-ids.js

  check_picturehouse:
    name: Check Picturehouse
    runs-on: self-hosted
    env:
      TZ: Europe/London
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - run: npm install
      - run: npx playwright install --with-deps
      - run: node node_modules/scripts/analysis/check-picturehouse-ids.js
