on:
  schedule:
    - cron: '0 18 * * 1'  # 18:00 UTC every Monday
  workflow_dispatch:

name: Reset dependencies on runners

jobs:
  reset-dependencies:
    name: Reset dependencies on ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - self-hosted-pi4-1
          - self-hosted-pi4-2
          - self-hosted-pi4-3
          - self-hosted-pi4-4
          - self-hosted-pi4-5
          - self-hosted-pi4-6
    steps:
      - uses: actions/checkout@v4

      - name: Set Playwright path
        run: echo "PLAYWRIGHT_BROWSERS_PATH=$HOME/.cache/playwright-browsers" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Clear npm cache
        run: |
          npm cache verify
          npm cache clean --force
          npm cache verify

      - name: Clear Playwright cache
        run: |
          if [ -d "$PLAYWRIGHT_BROWSERS_PATH" ]; then
            npx playwright uninstall --all
          else
            echo "No Playwright browsers directory found, skipping uninstall"
          fi

      - name: Install dependencies
        run: npm install

      - name: Install Playwright and dependencies
        run: npx playwright install --with-deps
